# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

     env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ENVIRONMENT: development  # or 'production'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set execute permissions for Docker Compose scripts
      run: |
        chmod +x ./scripts/docker-compose-up.sh
        chmod +x ./scripts/docker-compose-down.sh

    - name: Run Docker Compose Up Script
      run: ./scripts/docker-compose-up.sh

    - name: Wait for services to be ready
      run: |
        docker-compose exec -T inventory-service bash -c 'until pg_isready -h inventory-db -U postgres; do sleep 1; done'
    
    - name: Run tests for inventory-service
      run: docker-compose exec -T inventory-service poetry run pytest tests/

    - name: Run Docker Compose Down Script
      if: always()
      run: ./scripts/docker-compose-down.sh
