name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: inventory
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and start services
      run: docker-compose up -d --build

    - name: Wait for services to be ready
      run: |
        docker-compose exec -T inventory-service bash -c 'until pg_isready -h inventory-db -U postgres; do sleep 1; done'
    
    - name: Run tests for inventory-service
      run: docker-compose exec -T inventory-service poetry run pytest tests/

    # - name: Run tests for user-service
    #   run: docker-compose exec -T user-service poetry run pytest tests/

    - name: Tear down services
      if: always()
      run: docker-compose down
